services:
  frankenphp-builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp-builder
      args:
        PHP_VERSION: "8.4"
        PHP_EXTENSIONS: "ctype,curl,dom,fileinfo,intl,mbstring,opcache,pcntl,pdo_sqlite,phar,posix,session,shmop,simplexml,sockets,sodium,sysvmsg,sysvsem,sysvshm,tokenizer,xml,openssl,xmlreader,xmlwriter,zip,redis,igbinary,xhprof"
        PHP_EXTENSION_LIBS: "bzip2,freetype,libjpeg,libpng,libsodium,libzip,libxml2,zlib,icu,libxslt,libwebp"
        SPC_LIBC: "musl"
        CLASSIC: "1"
        MIMALLOC: "1"
      cache_from:
        - type=local,src=.buildkit-cache
      cache_to:
        - type=local,dest=.buildkit-cache,mode=max