name: Build FrankenPHP Docker Image

on: workflow_dispatch

jobs:
  build:
    name: Build & Push (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer and SPC
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer
            ~/.cache/static-php-cli
            /tmp/spc-downloads
          key: frankenphp-composer-${{ matrix.arch }}-${{ hashFiles('build-static.sh') }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push FrankenPHP builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/frankenphp-builder:latest-${{ matrix.arch }}

  manifest:
    name: Create & Push multi‑arch manifest
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push manifest list
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/frankenphp-builder:latest \
            ghcr.io/${{ github.repository_owner }}/frankenphp-builder:latest-amd64 \
            ghcr.io/${{ github.repository_owner }}/frankenphp-builder:latest-arm64
