name: Build FrankenPHP Docker Image

on: workflow_dispatch

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/frankenphp-builder
  PLATFORMS: linux/amd64,linux/arm64
  CACHE_SCOPE: ${{ github.ref_name || github.sha }}-frankenphp-builder

jobs:
  build:
    name: Build & Push Multi‑Arch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer & SPC
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer
            ~/.cache/static-php-cli
            /tmp/spc-downloads
          key: ${{ runner.os }}-composer-${{ hashFiles('build-static.sh') }}
          # (optional) restore-keys: composer-

      - name: Set up Docker Buildx + QEMU
        uses: docker/setup-buildx-action@v3
        with:
          install: true   # auto-installs qemu if needed

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push multi‑arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=${{ env.CACHE_SCOPE }}
          cache-to:   type=gha,scope=${{ env.CACHE_SCOPE }},mode=max
