name: Build FrankenPHP Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Push FrankenPHP Builder Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        arch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer and SPC
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer
            ~/.cache/static-php-cli
            /tmp/spc-downloads
          key: frankenphp-composer-${{ matrix.arch }}-${{ hashFiles('build-static.sh') }}

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frankenphp-builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/franken_builder:latest
